## Assignment 1

**Instructions:** <br>
a. write your answer after `# your answer here`. Do not delete any code that is in the cell, as the code facilitates checking your answers. If you happen to delete any code that prevents expected outputs, you may lose points. <br>
b. when you finish the assignment, make sure to use `Kernel` -> `Restart and Run All` to restart the kernel and rerun the entire notebook to generate the desired outputs, before submitting your assignment. <br>
c. upload your .ipynb file. <br>
<br>
Each question is worth 5 points.
### Python Types and Functions

1. Write a function to check if a given key (input1) already exists in a dictionary (input2), if true, return a tuple of the key and the value; if false, return None.

In [42]:
fruits = {'apple': 'red', 'pear': 'yellow', 'orange': 'orange', 'grape': 'purple'}
def is_key_present(input1, input2):
  # your answer here
  return input1 in input2

print(is_key_present('pear', fruits))
print(is_key_present('watermelon', fruits))

True
False


2. Create a function that takes a string as the input and returns a dictionary showing the number of characters in a string. <br>
Sample Input: 'apple pie' <br>
Output: {'a': 1, 'p': 3, 'l': 1, 'e': 2, ' ': 1, 'i': 1}

In [41]:
def char_frequency(string):
    # your answer here
    dic = {}
    for s in string:
      if s not in dic:
        dic[s] = 1
      else:
        dic[s] += 1

    return dic

print(char_frequency('apple pie'))

{'a': 1, 'p': 3, 'l': 1, 'e': 2, ' ': 1, 'i': 1}


3. Create a function that takes a string as the input and return a string that is made of the first 2 and the last 2 characters of the input string. If the string length is less than 2, return 'The length of the input string is shorter than 2!'. <br>
Sample String : 'carnivore' <br>
Expected Result : 'care' <br>
Sample String : 'hi' <br>
Expected Result : 'hihi' <br>
Sample String : '?' <br>
Expected Result : 'The length of the input string is shorter than 2!'

In [37]:
def string_start2_end2(str):
  # your answer here
  if len(str) < 2:
    return 'The length of the input string is shorter than 2!'
  first_two = str[0:2]
  last_two = str[len(str)-2:]
  return first_two + last_two


print(string_start2_end2('carnivore'))
print(string_start2_end2('hi'))
print(string_start2_end2('?'))

care
hihi
The length of the input string is shorter than 2!


4. Create a function that takes two inputs of lists and return an interwined list in this way: <br>
Sample input: <br>
listA = [1, 2, 3, 4]<br>
listB = ['a', 'b', 'c', 'd', 'e', 'f']<br>
Return:
[1, 'a', 2, 'b', 3, 'c', 4, 'd', 'e', 'f'].<br>
Note: when the lengths do not match, the remainder shall be appended to the end of the output list.

In [24]:
def interwine(A, B):
    # your answer here
    max_len = max(len(A), len(B))
    ans = []

    for i in range(max_len):
      if i < len(A):
        ans.append(A[i])
      if i < len(B):
        ans.append(B[i])

    return ans

listA = [1, 2, 3, 4]
listB = ['a', 'b', 'c', 'd', 'e', 'f']

print(interwine(listA, listB))
print(interwine(listB, listA))
print(interwine(listA, listA))

[1, 'a', 2, 'b', 3, 'c', 4, 'd', 'e', 'f']
['a', 1, 'b', 2, 'c', 3, 'd', 4, 'e', 'f']
[1, 1, 2, 2, 3, 3, 4, 4]


### Lambda

5. Write a function to extract year, month and day from datetime using Lambda, and print using the string formatting.<br>
Sample input:
now = 2020-09-10 22:24:17.072952<br>
Output: 'Year: 2020, month: 9, day: 10'<br> <br>
Example for string formatting:<br>
hello_statement = 'Hello, {}!'<br>
hello_statement.format('World')<br>

In [21]:
import datetime
now = datetime.datetime.now()
print(now)

def date_time(date):
    #use lambda to extract the information
    getYear = lambda x: x.year
    getMonth = lambda x: x.month
    getDay = lambda x: x.day

    year = getYear(date)
    month = getMonth(date)
    day = getDay(date)

    #string formatting
    date_str = 'Year: {}, month: {}, day: {}'
    return date_str.format(year, month, day)


date_time(now)

2023-09-26 13:03:41.594444


'Year: 2023, month: 9, day: 26'

6. Sort a list of tuples by the second element using Lambda.<br>
Sample input: [('Apple', 12), ('Pear', 2), ('Orange', 15), ('Banana', 0)] <br>
Output: [('Banana', 0), ('Pear', 2), ('Apple', 12), ('Orange', 15)]

In [13]:
before = [('Apple', 12), ('Pear', 2), ('Orange', 15), ('Banana', 0)]

# Use lambda to create an output list: your answer here
after = sorted(before, key=lambda x: x[1])

print("Original list of tuples:")
print(before)

print("\nSorted list of Tuples:")
print(after)

Original list of tuples:
[('Apple', 12), ('Pear', 2), ('Orange', 15), ('Banana', 0)]

Sorted list of Tuples:
[('Banana', 0), ('Pear', 2), ('Apple', 12), ('Orange', 15)]


7. Write a function to count the odd, even numbers in a given array of integers using Lambda. <br>
Sample input:  <br>
[1, 4, 3, 11, 7, 8, 15, 10]  <br>
Sample output:  <br>
Number of odd numbers: 5  <br>
Number of even numbers: 3  <br>

In [12]:
array_example = [1, 4, 3, 11, 7, 8, 15, 10]
def even_odd(array_numbers):
    # your answer here: variables 'odd' and 'even' are the counted numbers respectively
    # odd = len([n for n in array_numbers if n % 2 != 0])
    # even = len([n for n in array_numbers if n % 2 == 0])

    odd = len(list(filter(lambda x: x % 2 != 0, array_numbers)))
    even = len(list(filter(lambda x: x % 2 == 0, array_numbers)))

    print("Number of odd numbers: ", odd)
    print("Number of even numbers: ", even)

even_odd(array_example)

Number of odd numbers:  5
Number of even numbers:  3


### List Comprehension

8. Create a function that takes an input list of strings and returns (1) a list containing the length of each string and (2) a tuple containing the longest string and its index in the list. <br>
Note: you shall use list comprehension in the function.<br> <br>
Sample input: ['I', 'love', 'programming', 'using', 'Python'] <br>
Return: ([1, 4, 11, 5, 6], ('programming', 2)).

In [4]:
def find_longest_word(words_list):
    # list comprehension
    len_list = [len(w) for w in words_list]
    longest_word = max(words_list, key=len)

    # find index of the longest string
    index = words_list.index(longest_word)

    return (len_list, (longest_word, index))

print(find_longest_word(['I', 'love', 'programming', 'using', 'Python']))

([1, 4, 11, 5, 6], ('programming', 2))


### Numpy

9. Use numpy and arange to create a 2x4 matrix with values ranging from 2 to 9. <br>
Ouput:<br>
Expected Output:<br>
[[ 2 3 4 5]<br>
[ 6 7 8 9]]

In [90]:
import numpy as np
# your answer here
arr = np.arange(2, 10)
matrix = arr.reshape(2, 4)
print(matrix)


[[2 3 4 5]
 [6 7 8 9]]


10. Write a function to take an integer numpy array as the input, then (1) create an array that has the same values as the input array, and if there are odd numbers, add 1 to change them to even numbers, (2) stack the input array and the new array vertically, and (3) change the array to the float type (i.e. 'float32'). <br>
Sample input:<br>
[ 1  5  7 12 14] <br>
Output: <br>
[[ 1.  5.  7. 12. 14.]<br>
 [ 2.  6.  8. 12. 14.]]

In [91]:
import numpy as np
example = np.array([1, 5, 7, 12, 14],dtype='int32')
print(example,'\n')

def array_func(a):
    # your answer here
    arr = np.copy(a)
    arr[arr % 2 != 0] += 1
    ans = np.array([a, arr], dtype='float32')
    return ans

result = array_func(example)
print(result.dtype)
print(result)

[ 1  5  7 12 14] 

float32
[[ 1.  5.  7. 12. 14.]
 [ 2.  6.  8. 12. 14.]]


11. Use numpy to first create a 6 by 6 matrix and fill it with a checkerboard pattern. Then append a column of 2's to the left. <br>
Checkerboard pattern:<br>
[[2 0 1 0 1 0 1]                                                      
 [2 1 0 1 0 1 0]                                                      
 [2 0 1 0 1 0 1]                                                      
 [2 1 0 1 0 1 0]                                                      
 [2 0 1 0 1 0 1]                                                      
 [2 1 0 1 0 1 0]]

In [92]:
import numpy as np
print("A checkerboard pattern with 2's on the left:")
# your answer here
column = np.full([6,1], 2)

matrix = np.zeros((6, 6), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

merged = np.hstack((column, matrix))

print(merged)






A checkerboard pattern with 2's on the left:
[[2 1 0 1 0 1 0]
 [2 0 1 0 1 0 1]
 [2 1 0 1 0 1 0]
 [2 0 1 0 1 0 1]
 [2 1 0 1 0 1 0]
 [2 0 1 0 1 0 1]]


12. Write a function that obtains 1000 samples from normal distribution (mean=0, standard deviation=2) and calculate cosine for each of them. Then return an array that contains (1) the number of elements that is negative, (2) the mean, and (3) the 25th and 75th percentiles. Use numpy.round? to round your results to have three decimals. <br>
Sample output:<br>
array([390.   ,   0.173,  -0.477,   0.832])<br>

In [93]:
import numpy as np
np.set_printoptions(suppress=True)

def fun_cos():
    # your answer here
    samples = np.random.normal(loc=0, scale=2, size=1000)
    cos_samples = np.cos(samples)

    num_neg = np.sum(samples >= 0, axis=0)
    mean = np.round(np.mean(samples), 3)
    low_q = np.round(np.percentile(samples, 0.25), 3)
    high_q = np.round(np.percentile(samples, 0.75), 3)

    ans = np.array([num_neg, mean, low_q, high_q])

    return ans

np.random.seed(1234)
fun_cos()

array([507.   ,   0.031,  -5.191,  -4.767])